services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - db_data:/app/data
    environment:
      - DB_PATH=/app/data/ratings.db
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always

volumes:
  db_data:
