worker_processes 1;
pid /home/student/radiocalico/nginx/nginx.pid;
error_log /home/student/radiocalico/nginx/error.log;

events {
    worker_connections 256;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /home/student/radiocalico/nginx/access.log;
    sendfile on;

    server {
        listen 8088;
        server_name localhost;
        root /home/student/radiocalico;
        index index.html;

        location /api/ {
            proxy_pass http://127.0.0.1:8089;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
